# name属性用来指定这个工作流的名字
name: collectArticles

# 这个部分用来指定能够触发工作流执行的事件
on:
  # 当对分支main进行push操作的时候，这个工作流就被触发了
  push:
    branches: [ main ]
  schedule:
    # 定时任务
    - cron: "0 0/5 * * * ?"  # 每五分钟执行一次

# 工作流是由一个或多个的jobs构成的，在jobs里来说明要交给GitHub aciton执行的任务
jobs:
  # 这个jobs中的一个任务，名字叫build(随便怎么取)
  build:
    # 用来指定这个任务在什么操作系统上跑(服务器是GitHub免费提供的)
    runs-on: ubuntu-latest

    # 指出这个build任务的步骤
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    

      # 安装python环境
      - name: Install python
        uses: actions/setup-python@v2
        
      # 安装依赖
      - name: Install dependencies
        run: python -m pip install requests
        
      # 运行脚本
      - name: Run
        run: python collectArticles.py
        
      # 更新仓库
      - name: commit and push
        run: |
          git config --global user.email "1170516014@qq.com"
          git config --global user.name "y0lo-0924"
          git add .
          git commit -m "update"
          git push
